#!/bin/bash
SUITE_CMD=""

if [ -n "$SUITE" ]
then SUITE_CMD="-suite $SUITE"
fi

ct_run -noinput -noshell -config test/test.config -logdir logs -dir test $SUITE_CMD \
       -include ./ -erl_args -pa $PWD/ebin $PWD/deps/*/ebin
